### ISSUE TITLE
Multilingual Sitemap support

### ISSUE THREAD

**Issue by simongerads** [fabianmichael/kirby-meta#59]
The meta plugin works great on all languages only on the sitemap.xml it only shows the data of the default language. This is in general ok but it would be great if there would be an option to enable alternate links.

https://developers.google.com/search/blog/2012/05/multilingual-and-multinational-site?hl=de

**Comment by fabianmichael** [comment]
Hi, this feature should be included. The sitemap should links for all language versions of a page by default.

https://github.com/fabianmichael/kirby-meta/blob/main/src/Sitemap.php#L87

What’s still missing is the rendering of links in the document `<head>`. Can you give me a few more details about your project setup?

**Comment by sg-aix** [comment]
Hi, 
thanks for the sitemap feature explanation. It is absolutely correct. It is included, I just didn't seen. The problem I have is, that google doesn't accept the site in the search console. 


I think it is related to the following setup in my config: 
```
    'languages' => true,
    'languages.detect' => true,
```
    
the default, non multi language setup is not accepted since it is a forward to the auto detected language. The auto detected language is not accepted because google says it is a duplicate. 
    
You can check the website out at sambamba.net

**Comment by simongerads** [comment]
Hi,
thanks for the sitemap feature explanation. It is absolutely correct. It is included, I just didn't seen. The problem I have is, that google doesn't accept the site in the search console.

I think it is related to the following setup in my config:
```

    'languages' => true,
    'languages.detect' => true,
```
the default, non multi language setup is not accepted since it is a forward to the auto detected language. The auto detected language is not accepted because google says it is a duplicate.

You can check the website out at sambamba.net

**Comment by fabianmichael** [comment]
@simongerads Sorry, i cannot give you any further support with this. Never used the language autodetect feature myself. But if you find a solution, please feel free to share it here.
